### ISSUE TITLE
An active access token must be used to query information about the current user when trying to import contacts from facebook

### ISSUE THREAD

**Issue by tonyvince** [Diego81/omnicontacts#174] opened 2017-07-28 13:01 UTC
I have `gem 'omnicontacts', github: 'Diego81/omnicontacts'` in my Gemfile

and `omnicontacts.rb`
```ruby
Rails.application.middleware.use OmniContacts::Builder do
  importer :facebook, "xxxxxx", "xxxxxxx", { redirect_path: '/import_contacts/facebook/contact_callback' }
end
```
but I am getting

```
"error":{"message":"An active access token must be used to query information about the current user.","type":"OAuthException","code":2500,"fbtrace_id":"XXXXXXX"}}
```

How to fix this?

**Comment by mlennie** [comment] 2017-09-04 23:53
I'm getting same error

**Comment by katiemccann** [comment] 2017-10-19 23:41
This is a duplicate of https://github.com/Diego81/omnicontacts/issues/170, closing this one.

**Closed by katiemccann** 2017-10-19 23:41 UTC
